#!/bin/bash -l

# Load the require modules
module load ${R_MODULE}
module load ${RSTUDIO_MODULE}

# Start up the RStudio Server
echo "Starting up rserver..."

${PROOT_PATH} -b ${TMPDIR}:/tmp rserver --www-port ${HOST_PORT} --auth-none 0 --auth-pam-helper-path "${ROOT}/bin/auth" --auth-encrypt-password 0
