#!/bin/bash -l

# Load the R module
module load ${R_MODULE}

# Load the RStudio Module
module load ${RSTUDIO_MODULE}

# Launch RStudio Server
rserver --www-port ${HOST_PORT} --auth-none 0 --auth-pam-helper-path ~/awesim/dev/bc_rstudio_server/template/binary_helper --auth-encrypt-password 0
